import type { Metadata } from "next";
import "./../assets/styles/main.css";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js">
      <body suppressHydrationWarning data-gramm="false">
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
