import type { Metadata } from "next";
import "./../assets/styles/main.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning data-gramm="false">
        {children}
      </body>
    </html>
  );
}
